device: "cuda"

audio:
  sample_rate: 32000
  chunk_length: 10
  fade_sec: 1.0
  min_chunk_sec: 5.0

snac:
  model: "hubertsiuzdak/snac_32khz"
  codebook_size: 4096
  n_levels: 4

  generation:
    temperature: 1.0
    top_k: 50

  inference:
    batch_size: 32
    num_workers: 8

data:
  token_dir: "data/snac_tokens"
  segment_dir: "data/segments"
  val_ratio: 0.05
  test_ratio: 0.05
  seed: 42
  min_samples_per_class: 50

pretrain:
  epochs: 2
  batch_size: 16
  learning_rate: 1.0e-4
  warmup_steps: 1000
  max_seq_len: 1620
  num_workers: 8
  save_dir: "checkpoints/gpt2"

model:
  backbone: "llama"
  n_embd: 768
  n_layer: 12
  n_head: 12
  n_positions: 1664

wandb:
  project: "ar-bird-vocalization"
  entity: "hamula-dm-ukrainian-catholic-university"

audiogen:
  pretrained: "facebook/audiogen-medium"
  sample_rate: 16000
  target_length: 10
  save_dir: "checkpoints/audiogen"
  num_workers: 8
  grad_accum: 1

  encodec_tokens:
    dir: "data/encodec_tokens"

  encodec_inference:
    batch_size: 32
    num_workers: 8

  stage1:
    epochs: 20
    batch_size: 8
    learning_rate: 1.0e-3
    warmup_steps: 100

  stage2:
    epochs: 50
    batch_size: 4
    learning_rate: 2.0e-4
    warmup_steps: 100
    lora:
      enabled: true
      rank: 16
      alpha: 32

  stage3:
    epochs: 50
    batch_size: 4
    learning_rate: 5.0e-5
    warmup_steps: 500
    lora:
      enabled: true
      rank: 16
      alpha: 32

  generation:
    duration: 10.0
    temperature: 1.0
    top_k: 250
    cfg_coef: 3.0

s3:
  bucket: "ar-bird-vocalization-dataset"
  prefix: "tokens"

birdclef:
  data_dir: "data/birdclef-2026"
  segment_dir: "data/birdclef_segments"
  convnext_labels: "data/convnext.json"
  taxonomy_csv: "data/csvs/ebird_taxonomy.csv"
  top_k: 5
  max_entropy: 3.0
  min_samples_per_class: 20

# Reference: https://huggingface.co/DBD-research-group/ConvNeXT-Base-BirdSet-XCL
evaluation:
  batch_size: 16
  num_workers: 8
  sample_rate: 32000
  model_checkpoint: "DBD-research-group/ConvNeXT-Base-BirdSet-XCL"
  n_fft: 1024
  hop_length: 320
  n_mels: 128
  spec_mean: -4.268
  spec_std: 4.569
  spec_size: [256, 417]
